server.port: 8081

# Spring boot performs autoconnection to embedded mongodb, hence even if no port provide it performs lookup.
#spring.data.mongodb.port: 0


  # Below configuration for raw kafka connection  
#  kafka:
#    producer:
#        bootstrap-servers: localhost:9081
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    admin:
#      fail-fast: true
  
springdoc.api-docs.path: /order-docs

spring:
  application:
    name: tiny-saga-order-ms
  kafka:
    bootstrap-servers: kafka:9092 # 192.168.29.53:9092 # kafka:9092 use this host when running kafka and app in docker
    group_id: order-ms



  
