server.port: 8081

# Spring boot performs autoconnection to embedded mongodb, hence even if no port provide it performs lookup.
#spring.data.mongodb.port: 0


  # Below configuration for raw kafka connection  
#  kafka:
#    producer:
#        bootstrap-servers: localhost:9081
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    admin:
#      fail-fast: true
  
springdoc.api-docs.path: /order-docs

spring:
  application:
    name: tiny-saga-order-ms
  kafka:
    bootstrap-servers: localhost:29092
    group_id: order-ms

  
