openapi: 3.0.3
info:
  title: Payment API
  version: 1.0.0
paths:
  /v2/api/payment/dev/healthcheck:
    get:
      summary: Get Health Check. This API Used in Orchestrator saga pattern.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
                {
                   "status": 200,
                   "responseMessage": "Payment server and Trabsactuib DB is up and running"
                 }
  /v2/api/payment/dev/transactions:
    get:
      summary: Get All Transactions. This API used for development/debugging purpose.
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "amount": 100.0,
                    "orderId": "ABC123",
                    "timestamp": "2024-02-03T12:34:56Z"
                  },
                  {
                    "id": 2,
                    "amount": 150.0,
                    "orderId": "XYZ789",
                    "timestamp": "2024-02-03T13:45:00Z"
                  }
                ]
  /v2/api/payment/dev/transactions/order:
    get:
      summary: Get Transactions for given order id. This API used for development/debugging purpose.
      parameters:
        - name: orderId
          in: query
          required: true
          schema:
            type: string
          example: ABC123
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "amount": 100.0,
                    "orderId": "ABC123",
                    "timestamp": "2024-02-03T12:34:56Z"
                  }
                ]
  /v2/api/payment/order/pay:
    post:
      summary: Process Payment for given Order id.  This API Used in Orchestrator saga
        pattern.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentProcessRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Response'
              example: |
               {
                  "status": 200,
                  "responseMessage": "Payment processed succesfully"
                }
        '400':
          description: Authorization error
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Response'
              example: |
                {
                  "status": 400,
                  "responseMessage": "Payment cannot be proceed, due to insufficient fund"
                }
        '401':
          description: Authorization error
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Response'
              example: |
                {
                  "status": 401,
                  "responseMessage": "Authorization exception occured"
                }
        '404':
          description: Authorization error
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Response'
              example: |
                {
                  "status": 404,
                  "responseMessage": "User not found in backend"
                }
        '500':
          description: Server error
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Response'
              example: |
                {
                  "status": 500,
                  "responseMessage": "Server error occured"
                }
          
components:
  schemas:
    PaymentProcessRequest:
      type: object
      required: 
        - correlationId
        - orderId
        - userId
        - orderStatus
        - paymentProcessType
        - paymentType
      properties:
        correlationId:
          type: string
        orderId:
          type: string
        userId:
          type: string
        orderStatus:
          type: string
          enum:
            - INITIATED
            - INITIATED
            - ORDER_DELIEVERED
            - ORDER_FAIL
        paymentProcessType:
          type: string
          enum:
            - PAY
            - REFUND
        paymentType:
          type: string
          enum:
            - Wallet
            - PAYPAL
        productId:
          type: string
        productQuantity:
          type: integer
        price:
          type: integer
        paymentFailReason:
          type: string
    Response:
      type: object
      properties:
        status:
          type: integer
        responseMessage:
          type: string
      required:
        - status
        - responseMessage
    
