server:
  port: 8084
  
springdoc.api-docs.path: /orchestrator-docs


spring:
  kafka:
    bootstrap-servers: kafka:9092
    group_id: orchestrator-ms
    
services:
  payment:
    host: 172.20.0.6
    port: 8087
    protocol: http
    orderPayPath: "/v2/api/payment/order/pay"
  inventory:
    host: 172.20.0.6
    port: 8088
    protocol: http
    reserveInventoryPath: "/v2/api/inventory/reserve/product/{productId}"
  order:
    host: 172.20.0.6
    port: 8081
    protocol: http
    updateOrderStatusPath: "/v2/api/order/{orderId}/status"

  