openapi: 3.0.3
info:
  title: Inventory API
  version: 1.0.0
paths:
  /v2/api/inventory/dev/healthcheck:
    get:
      summary: Get Health Check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: 'ok ok health from transaction'
  /v2/api/inventory/reserve/product/{productId}:
   put:
      summary: Update inventory reservation for a product
      description: Update the reservation quantity for a specific product in the inventory.
      parameters:
        - name: productId
          in: path
          description: ID of the product to update reservation
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 12
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: |
               {
                  "status": 200,
                  "responseMessage": "Inventory updated succesfully"
                }
        '401':
          description: Authorization error
          content:
            application/json:
              example: |
                {
                  "status": 401,
                  "responseMessage": "Authorization exception occured"
                }
        '500':
          description: Server error
          content:
            application/json:
              example: |
                {
                  "status": 500,
                  "responseMessage": "Server error occured"
                }
          
