name: Maven Clean Install Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: List files and directories
      run: |
        pwd
        env
        java -version
        mvn -version

    - name: Maven Clean Install
      run: |
        ms_list=("tiny-saga-inventory-ms" "tiny-saga-wallet-ms" "tiny-saga-order-ms" "tiny-saga-payment-ms" "tiny-saga-order-ms")
        for folder in "${ms_list[@]}";  do
          cd $folder
          echo "Building service: $folder"
          mvn -q clean install
          if [ $? -eq 0 ]; then
            echo "Maven build successful for $folder"
          else
            echo "Maven build failed for $folder"
            exit 1
          fi
          cd ..
        done

